Fix schema
deepsourcelabs/murdock pull request #17
Opened 2022-03-05 10:41 UTC by NobleMathews

Modify schema based on the discussion in #7 
Fix a few dynamic cases in python
Pending Testing for all languages

2022-03-15 06:03 UTC, NobleMathews commented
Older tests need to be updated to work with new schema
Github token required for tests to complete (>50)
Lock file-based tests disabled - to discuss along with version-specific handling

2022-04-25 07:14 UTC, tushar-deepsource requested changes

2022-04-25 07:14 UTC, tushar-deepsource commented on tests/test_dependency_files.py
> -    assert result["version"] == "0.0.1"
keep some value checks alongside the schema checks, to be completely sure.

2022-04-25 07:14 UTC, tushar-deepsource commented on tests/test_inspector.py
> +    assert result["pkg_dep"]
is this a non-zero check? please change it to `len(result["pkg_dep"]) != 0` etc. to clarify what this assert is testing.

2022-04-25 07:14 UTC, tushar-deepsource commented on mypy.ini
> +exclude = tests
```suggestion
exclude = tests

```

2022-04-25 07:14 UTC, tushar-deepsource commented on error.py
> +        self.msg = f"{file} is currently not supported"
simply assigning `self.msg` doesn't work, you have to do `super().__init__(self.msg)`

2022-04-25 10:11 UTC, NobleMathews commented on tests/test_inspector.py
> +    assert result["pkg_dep"]
It used to be like that but Srijan asked me to change so that len(..) is not used unnecessarily

2022-04-25 10:18 UTC, tushar-deepsource commented on tests/test_inspector.py
> +    assert result["pkg_dep"]
Sorry about that :") Please revert it to `len(...) != 0` checks. It also avoids accidental falsey values like `None`.

```console
$ python -m this | grep Explicit
Explicit is better than implicit.
```

2022-04-25 11:11 UTC, NobleMathews commented on tests/test_dependency_files.py
> -    assert result["version"] == "0.0.1"
If it's alright I will address this in the DB pull since I want to change the sample data to have a bit more variety and remove some of the files that were causing empty entries in the DB

2022-04-26 08:05 UTC, tushar-deepsource commented on tests/test_dependency_files.py
> -    assert result["version"] == "0.0.1"
That's fine.

2022-05-13 09:08 UTC, tushar-deepsource commented
/approve

2022-05-13 09:08 UTC, tushar-deepsource approved these changes

2022-05-13 09:09 UTC, merged