Adds support for Postgres Databases
deepsourcelabs/murdock pull request #30
Opened 2022-05-21 04:44 UTC by NobleMathews

Remove Elastic DB related logic
Adds support for Postgres test and production databases

---
Reimplemented due to git issues

2022-05-31 14:31 UTC, tushar-deepsource requested changes

2022-05-31 14:31 UTC, tushar-deepsource commented on cli.py
> +    lang: str = typer.Option(None),
why is this set back to `None`? This is a required parameter

2022-05-31 14:31 UTC, tushar-deepsource commented on cli.py
> +        if not db_name:
Why is db name optional anyway?

2022-05-31 14:31 UTC, tushar-deepsource commented on dependencies/helper.py
> -    if version is not None:
why is this changed?

2022-05-31 14:37 UTC, NobleMathews commented on cli.py
> +        if not db_name:
You can run the package without using the database, the initial plan was to keep the DB internal

2022-05-31 14:42 UTC, NobleMathews commented on cli.py
> +    lang: str = typer.Option(None),
Ah my bad

2022-05-31 14:55 UTC, NobleMathews commented on cli.py
> +        if not db_name:
Sure i will look into it in another PR

2022-06-09 11:47 UTC, tushar-deepsource commented
@NobleMathews Please add some example CLI commands along with the database configuration required to test this

2022-06-26 17:30 UTC, tushar-deepsource approved these changes

2022-06-26 17:30 UTC, merged