feat: Add support for C#
deepsourcelabs/murdock pull request #35
Opened 2022-05-30 11:45 UTC by NobleMathews

Implements task from https://github.com/deepsourcelabs/murdock/issues/21

Adds support for C#

Checks .nuspec file for package metadata

Retrieves data from NuGet API

2022-06-10 06:17 UTC, pawan-deepsource commented on dependencies/go/go_worker.py
> +        "MinGoVer": "lang_ve    r",
Is this intentional?

2022-06-10 10:10 UTC, NobleMathews commented on dependencies/go/go_worker.py
> +        "MinGoVer": "lang_ve    r",
Nope my bad, fixed thanks!

2022-06-27 11:16 UTC, tushar-deepsource requested changes

2022-06-27 11:16 UTC, tushar-deepsource commented on tests/test_inspector.py
> +    """Test version and license for javascript"""
s/javascript/c#

2022-06-27 11:16 UTC, tushar-deepsource commented on tests/test_inspector.py
> +    """Test version and license for javascript"""
s/javascript/c#

2022-06-27 11:25 UTC, tushar-deepsource approved these changes

2022-06-27 11:25 UTC, merged