Single Version Query Logic
deepsourcelabs/murdock pull request #41
Opened 2022-06-24 22:28 UTC by NobleMathews

Implements single version querying
Adds support for parsing non-specific requirements
Modified semver parsing with assumptions made for version not compliant with semver
Fixes Postgres DB return type and integration with other responses

2022-06-28 13:04 UTC, tushar-deepsource requested changes

2022-06-28 13:04 UTC, tushar-deepsource commented on dependencies/helper.py
> +def resolve_version(vers: List[str], reqs=None) -> str:
This will have to be refactored into self-sufficient documented functions

2022-06-28 20:37 UTC, NobleMathews commented on dependencies/py/py_helper.py
> +            res["pkg_dep"].append(str(ir.key) + "|" + str(ir.specs))
Will do it in another PR, need to modify quite a bit

2022-06-29 21:05 UTC, tushar-deepsource requested changes

2022-06-29 21:05 UTC, tushar-deepsource commented on dependencies/helper.py
> +                    filter(find_older_versions(ver, include_ver="=" in sym), vers)
The logic here is a bit weird to me, and I find the code of `find_older_versions` a bit hard to follow. And the `x in sym` checks I don't like, for example.

Can we do something like this instead?

```python
elif sym in ('>', '>=', '<', '<='):
    parsed_versions = [VersionInfo.parse(version) for version in vers]
    version = VersionInfo.parse(ver)
    if sym == '>':
        compatible_vers = [str(x) for x in parsed_versions x > version]
    if sym == '>=':
        compatible_vers = [str(x) for x in parsed_versions x >= version]
    if sym == '<':
        compatible_vers = [str(x) for x in parsed_versions x < version]
    if sym == '<=':
        compatible_vers = [str(x) for x in parsed_versions x <= version]
```

2022-06-30 12:21 UTC, tushar-deepsource commented on dependencies/helper.py
> +    elif dot_count >= 2:
```suggestion
    if dot_count <= 1:
        vers = [x for x in vers if semver.VersionInfo.parse(x).major == svi.major]
    else:
```

2022-06-30 12:26 UTC, tushar-deepsource submitted a review, later dismissed

2022-06-30 13:59 UTC, tushar-deepsource approved these changes

2022-06-30 13:59 UTC, merged